// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: app/app/api/app.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilUsdtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval  string `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Limit     string `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *FilUsdtRequest) Reset() {
	*x = FilUsdtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilUsdtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilUsdtRequest) ProtoMessage() {}

func (x *FilUsdtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilUsdtRequest.ProtoReflect.Descriptor instead.
func (*FilUsdtRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{0}
}

func (x *FilUsdtRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FilUsdtRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *FilUsdtRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *FilUsdtRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *FilUsdtRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type FilUsdtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataListK []*FilUsdtReply_ListK `protobuf:"bytes,1,rep,name=dataListK,proto3" json:"dataListK,omitempty"`
}

func (x *FilUsdtReply) Reset() {
	*x = FilUsdtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilUsdtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilUsdtReply) ProtoMessage() {}

func (x *FilUsdtReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilUsdtReply.ProtoReflect.Descriptor instead.
func (*FilUsdtReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{1}
}

func (x *FilUsdtReply) GetDataListK() []*FilUsdtReply_ListK {
	if x != nil {
		return x.DataListK
	}
	return nil
}

type SetPerSecondDFilTotalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPerSecondDFilTotalRequest) Reset() {
	*x = SetPerSecondDFilTotalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPerSecondDFilTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPerSecondDFilTotalRequest) ProtoMessage() {}

func (x *SetPerSecondDFilTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPerSecondDFilTotalRequest.ProtoReflect.Descriptor instead.
func (*SetPerSecondDFilTotalRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{2}
}

type SetPerSecondDFilTotalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPerSecondDFilTotalReply) Reset() {
	*x = SetPerSecondDFilTotalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPerSecondDFilTotalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPerSecondDFilTotalReply) ProtoMessage() {}

func (x *SetPerSecondDFilTotalReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPerSecondDFilTotalReply.ProtoReflect.Descriptor instead.
func (*SetPerSecondDFilTotalReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{3}
}

type GetPerSecondDFilTotalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime int64 `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64 `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *GetPerSecondDFilTotalRequest) Reset() {
	*x = GetPerSecondDFilTotalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondDFilTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondDFilTotalRequest) ProtoMessage() {}

func (x *GetPerSecondDFilTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondDFilTotalRequest.ProtoReflect.Descriptor instead.
func (*GetPerSecondDFilTotalRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{4}
}

func (x *GetPerSecondDFilTotalRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetPerSecondDFilTotalRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetPerSecondDFilTotalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataListDFil []*GetPerSecondDFilTotalReply_ListDfil `protobuf:"bytes,1,rep,name=dataListDFil,proto3" json:"dataListDFil,omitempty"`
}

func (x *GetPerSecondDFilTotalReply) Reset() {
	*x = GetPerSecondDFilTotalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondDFilTotalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondDFilTotalReply) ProtoMessage() {}

func (x *GetPerSecondDFilTotalReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondDFilTotalReply.ProtoReflect.Descriptor instead.
func (*GetPerSecondDFilTotalReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{5}
}

func (x *GetPerSecondDFilTotalReply) GetDataListDFil() []*GetPerSecondDFilTotalReply_ListDfil {
	if x != nil {
		return x.DataListDFil
	}
	return nil
}

type SetPerSecondPairInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPerSecondPairInfoRequest) Reset() {
	*x = SetPerSecondPairInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPerSecondPairInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPerSecondPairInfoRequest) ProtoMessage() {}

func (x *SetPerSecondPairInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPerSecondPairInfoRequest.ProtoReflect.Descriptor instead.
func (*SetPerSecondPairInfoRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{6}
}

type SetPerSecondPairInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPerSecondPairInfoReply) Reset() {
	*x = SetPerSecondPairInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPerSecondPairInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPerSecondPairInfoReply) ProtoMessage() {}

func (x *SetPerSecondPairInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPerSecondPairInfoReply.ProtoReflect.Descriptor instead.
func (*SetPerSecondPairInfoReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{7}
}

type GetPerSecondPairInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime int64  `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pair      string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *GetPerSecondPairInfoRequest) Reset() {
	*x = GetPerSecondPairInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondPairInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondPairInfoRequest) ProtoMessage() {}

func (x *GetPerSecondPairInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondPairInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPerSecondPairInfoRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{8}
}

func (x *GetPerSecondPairInfoRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetPerSecondPairInfoRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetPerSecondPairInfoRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetPerSecondPairInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataListPair []*GetPerSecondPairInfoReply_ListPair `protobuf:"bytes,1,rep,name=dataListPair,proto3" json:"dataListPair,omitempty"`
}

func (x *GetPerSecondPairInfoReply) Reset() {
	*x = GetPerSecondPairInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondPairInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondPairInfoReply) ProtoMessage() {}

func (x *GetPerSecondPairInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondPairInfoReply.ProtoReflect.Descriptor instead.
func (*GetPerSecondPairInfoReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{9}
}

func (x *GetPerSecondPairInfoReply) GetDataListPair() []*GetPerSecondPairInfoReply_ListPair {
	if x != nil {
		return x.DataListPair
	}
	return nil
}

type ReqContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractType string `protobuf:"bytes,1,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
}

func (x *ReqContractRequest) Reset() {
	*x = ReqContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqContractRequest) ProtoMessage() {}

func (x *ReqContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqContractRequest.ProtoReflect.Descriptor instead.
func (*ReqContractRequest) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{10}
}

func (x *ReqContractRequest) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

type ReqContractReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqContractReply) Reset() {
	*x = ReqContractReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqContractReply) ProtoMessage() {}

func (x *ReqContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqContractReply.ProtoReflect.Descriptor instead.
func (*ReqContractReply) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{11}
}

type FilUsdtReply_ListK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime           int64   `protobuf:"varint,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime             int64   `protobuf:"varint,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	StartPrice          float64 `protobuf:"fixed64,3,opt,name=StartPrice,proto3" json:"StartPrice,omitempty"`
	TopPrice            float64 `protobuf:"fixed64,4,opt,name=TopPrice,proto3" json:"TopPrice,omitempty"`
	LowPrice            float64 `protobuf:"fixed64,5,opt,name=LowPrice,proto3" json:"LowPrice,omitempty"`
	EndPrice            float64 `protobuf:"fixed64,6,opt,name=EndPrice,proto3" json:"EndPrice,omitempty"`
	DealTotalAmount     float64 `protobuf:"fixed64,7,opt,name=DealTotalAmount,proto3" json:"DealTotalAmount,omitempty"`
	DealAmount          float64 `protobuf:"fixed64,8,opt,name=DealAmount,proto3" json:"DealAmount,omitempty"`
	DealTotal           int64   `protobuf:"varint,9,opt,name=DealTotal,proto3" json:"DealTotal,omitempty"`
	DealSelfTotalAmount float64 `protobuf:"fixed64,10,opt,name=DealSelfTotalAmount,proto3" json:"DealSelfTotalAmount,omitempty"`
	DealSelfAmount      float64 `protobuf:"fixed64,11,opt,name=DealSelfAmount,proto3" json:"DealSelfAmount,omitempty"`
}

func (x *FilUsdtReply_ListK) Reset() {
	*x = FilUsdtReply_ListK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilUsdtReply_ListK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilUsdtReply_ListK) ProtoMessage() {}

func (x *FilUsdtReply_ListK) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilUsdtReply_ListK.ProtoReflect.Descriptor instead.
func (*FilUsdtReply_ListK) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FilUsdtReply_ListK) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetStartPrice() float64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetTopPrice() float64 {
	if x != nil {
		return x.TopPrice
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetDealTotalAmount() float64 {
	if x != nil {
		return x.DealTotalAmount
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetDealAmount() float64 {
	if x != nil {
		return x.DealAmount
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetDealTotal() int64 {
	if x != nil {
		return x.DealTotal
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetDealSelfTotalAmount() float64 {
	if x != nil {
		return x.DealSelfTotalAmount
	}
	return 0
}

func (x *FilUsdtReply_ListK) GetDealSelfAmount() float64 {
	if x != nil {
		return x.DealSelfAmount
	}
	return 0
}

type GetPerSecondDFilTotalReply_ListDfil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	TotalSupply string `protobuf:"bytes,2,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
}

func (x *GetPerSecondDFilTotalReply_ListDfil) Reset() {
	*x = GetPerSecondDFilTotalReply_ListDfil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondDFilTotalReply_ListDfil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondDFilTotalReply_ListDfil) ProtoMessage() {}

func (x *GetPerSecondDFilTotalReply_ListDfil) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondDFilTotalReply_ListDfil.ProtoReflect.Descriptor instead.
func (*GetPerSecondDFilTotalReply_ListDfil) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetPerSecondDFilTotalReply_ListDfil) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GetPerSecondDFilTotalReply_ListDfil) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

type GetPerSecondPairInfoReply_ListPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Reserve0 string `protobuf:"bytes,2,opt,name=reserve0,proto3" json:"reserve0,omitempty"`
	Reserve1 string `protobuf:"bytes,3,opt,name=reserve1,proto3" json:"reserve1,omitempty"`
}

func (x *GetPerSecondPairInfoReply_ListPair) Reset() {
	*x = GetPerSecondPairInfoReply_ListPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_api_app_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerSecondPairInfoReply_ListPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerSecondPairInfoReply_ListPair) ProtoMessage() {}

func (x *GetPerSecondPairInfoReply_ListPair) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_api_app_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerSecondPairInfoReply_ListPair.ProtoReflect.Descriptor instead.
func (*GetPerSecondPairInfoReply_ListPair) Descriptor() ([]byte, []int) {
	return file_app_app_api_app_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetPerSecondPairInfoReply_ListPair) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GetPerSecondPairInfoReply_ListPair) GetReserve0() string {
	if x != nil {
		return x.Reserve0
	}
	return ""
}

func (x *GetPerSecondPairInfoReply_ListPair) GetReserve1() string {
	if x != nil {
		return x.Reserve1
	}
	return ""
}

var File_app_app_api_app_proto protoreflect.FileDescriptor

var file_app_app_api_app_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x55, 0x73, 0x64, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xbf, 0x03, 0x0a, 0x0c, 0x46, 0x69, 0x6c,
	0x55, 0x73, 0x64, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x55, 0x73, 0x64, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x5f, 0x6b, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x4b, 0x1a, 0xf6, 0x02, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x6b, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x45, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x44, 0x65, 0x61, 0x6c,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0f, 0x44, 0x65, 0x61, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x44, 0x65, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x61, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x65, 0x61, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x30, 0x0a, 0x13, 0x44, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x6c, 0x66, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x44,
	0x65, 0x61, 0x6c, 0x53, 0x65, 0x6c, 0x66, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x6c, 0x66, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x44, 0x65, 0x61, 0x6c,
	0x53, 0x65, 0x6c, 0x66, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x56, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xaf, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4d, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x46, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x64, 0x66, 0x69, 0x6c,
	0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x46, 0x69, 0x6c, 0x1a, 0x42,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x64, 0x66, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x69,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61,
	0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0xc2, 0x01, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x69, 0x72, 0x1a, 0x57, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x31, 0x22, 0x39,
	0x0a, 0x12, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x71,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xfb, 0x05,
	0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x53, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x55, 0x73, 0x64, 0x74,
	0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x55, 0x73, 0x64, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x55,
	0x73, 0x64, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a,
	0x12, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x66, 0x69, 0x6c, 0x5f, 0x75, 0x73, 0x64, 0x74, 0x12, 0x8e, 0x01, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2b,
	0x12, 0x29, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x5f, 0x64, 0x66, 0x69, 0x6c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x8e, 0x01, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x46, 0x69, 0x6c, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x2b, 0x12, 0x29, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x5f, 0x64, 0x66, 0x69, 0x6c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x8a, 0x01, 0x0a,
	0x14, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12,
	0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f,
	0x70, 0x61, 0x69, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x8a, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x69,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x63, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72,
	0x65, 0x71, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x11, 0x0a, 0x03, 0x61,
	0x70, 0x69, 0x50, 0x01, 0x5a, 0x08, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_app_api_app_proto_rawDescOnce sync.Once
	file_app_app_api_app_proto_rawDescData = file_app_app_api_app_proto_rawDesc
)

func file_app_app_api_app_proto_rawDescGZIP() []byte {
	file_app_app_api_app_proto_rawDescOnce.Do(func() {
		file_app_app_api_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_app_api_app_proto_rawDescData)
	})
	return file_app_app_api_app_proto_rawDescData
}

var file_app_app_api_app_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_app_app_api_app_proto_goTypes = []interface{}{
	(*FilUsdtRequest)(nil),                      // 0: api.FilUsdtRequest
	(*FilUsdtReply)(nil),                        // 1: api.FilUsdtReply
	(*SetPerSecondDFilTotalRequest)(nil),        // 2: api.SetPerSecondDFilTotalRequest
	(*SetPerSecondDFilTotalReply)(nil),          // 3: api.SetPerSecondDFilTotalReply
	(*GetPerSecondDFilTotalRequest)(nil),        // 4: api.GetPerSecondDFilTotalRequest
	(*GetPerSecondDFilTotalReply)(nil),          // 5: api.GetPerSecondDFilTotalReply
	(*SetPerSecondPairInfoRequest)(nil),         // 6: api.SetPerSecondPairInfoRequest
	(*SetPerSecondPairInfoReply)(nil),           // 7: api.SetPerSecondPairInfoReply
	(*GetPerSecondPairInfoRequest)(nil),         // 8: api.GetPerSecondPairInfoRequest
	(*GetPerSecondPairInfoReply)(nil),           // 9: api.GetPerSecondPairInfoReply
	(*ReqContractRequest)(nil),                  // 10: api.ReqContractRequest
	(*ReqContractReply)(nil),                    // 11: api.ReqContractReply
	(*FilUsdtReply_ListK)(nil),                  // 12: api.FilUsdtReply.List_k
	(*GetPerSecondDFilTotalReply_ListDfil)(nil), // 13: api.GetPerSecondDFilTotalReply.List_dfil
	(*GetPerSecondPairInfoReply_ListPair)(nil),  // 14: api.GetPerSecondPairInfoReply.List_pair
}
var file_app_app_api_app_proto_depIdxs = []int32{
	12, // 0: api.FilUsdtReply.dataListK:type_name -> api.FilUsdtReply.List_k
	13, // 1: api.GetPerSecondDFilTotalReply.dataListDFil:type_name -> api.GetPerSecondDFilTotalReply.List_dfil
	14, // 2: api.GetPerSecondPairInfoReply.dataListPair:type_name -> api.GetPerSecondPairInfoReply.List_pair
	0,  // 3: api.App.FilUsdt:input_type -> api.FilUsdtRequest
	2,  // 4: api.App.SetPerSecondDFilTotal:input_type -> api.SetPerSecondDFilTotalRequest
	4,  // 5: api.App.GetPerSecondDFilTotal:input_type -> api.GetPerSecondDFilTotalRequest
	6,  // 6: api.App.SetPerSecondPairInfo:input_type -> api.SetPerSecondPairInfoRequest
	8,  // 7: api.App.GetPerSecondPairInfo:input_type -> api.GetPerSecondPairInfoRequest
	10, // 8: api.App.ReqContract:input_type -> api.ReqContractRequest
	1,  // 9: api.App.FilUsdt:output_type -> api.FilUsdtReply
	3,  // 10: api.App.SetPerSecondDFilTotal:output_type -> api.SetPerSecondDFilTotalReply
	5,  // 11: api.App.GetPerSecondDFilTotal:output_type -> api.GetPerSecondDFilTotalReply
	7,  // 12: api.App.SetPerSecondPairInfo:output_type -> api.SetPerSecondPairInfoReply
	9,  // 13: api.App.GetPerSecondPairInfo:output_type -> api.GetPerSecondPairInfoReply
	11, // 14: api.App.ReqContract:output_type -> api.ReqContractReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_app_app_api_app_proto_init() }
func file_app_app_api_app_proto_init() {
	if File_app_app_api_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_app_api_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilUsdtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilUsdtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPerSecondDFilTotalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPerSecondDFilTotalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondDFilTotalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondDFilTotalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPerSecondPairInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPerSecondPairInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondPairInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondPairInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqContractReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilUsdtReply_ListK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondDFilTotalReply_ListDfil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_api_app_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPerSecondPairInfoReply_ListPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_app_api_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_app_api_app_proto_goTypes,
		DependencyIndexes: file_app_app_api_app_proto_depIdxs,
		MessageInfos:      file_app_app_api_app_proto_msgTypes,
	}.Build()
	File_app_app_api_app_proto = out.File
	file_app_app_api_app_proto_rawDesc = nil
	file_app_app_api_app_proto_goTypes = nil
	file_app_app_api_app_proto_depIdxs = nil
}
