// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/app/api/app.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FilUsdtRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FilUsdtRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FilUsdtRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FilUsdtRequestMultiError,
// or nil if none found.
func (m *FilUsdtRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FilUsdtRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Symbol

	// no validation rules for Interval

	// no validation rules for Limit

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return FilUsdtRequestMultiError(errors)
	}

	return nil
}

// FilUsdtRequestMultiError is an error wrapping multiple validation errors
// returned by FilUsdtRequest.ValidateAll() if the designated constraints
// aren't met.
type FilUsdtRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FilUsdtRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FilUsdtRequestMultiError) AllErrors() []error { return m }

// FilUsdtRequestValidationError is the validation error returned by
// FilUsdtRequest.Validate if the designated constraints aren't met.
type FilUsdtRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilUsdtRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilUsdtRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilUsdtRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilUsdtRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilUsdtRequestValidationError) ErrorName() string { return "FilUsdtRequestValidationError" }

// Error satisfies the builtin error interface
func (e FilUsdtRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilUsdtRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilUsdtRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilUsdtRequestValidationError{}

// Validate checks the field values on FilUsdtReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FilUsdtReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FilUsdtReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FilUsdtReplyMultiError, or
// nil if none found.
func (m *FilUsdtReply) ValidateAll() error {
	return m.validate(true)
}

func (m *FilUsdtReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDataListK() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FilUsdtReplyValidationError{
						field:  fmt.Sprintf("DataListK[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FilUsdtReplyValidationError{
						field:  fmt.Sprintf("DataListK[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FilUsdtReplyValidationError{
					field:  fmt.Sprintf("DataListK[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FilUsdtReplyMultiError(errors)
	}

	return nil
}

// FilUsdtReplyMultiError is an error wrapping multiple validation errors
// returned by FilUsdtReply.ValidateAll() if the designated constraints aren't met.
type FilUsdtReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FilUsdtReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FilUsdtReplyMultiError) AllErrors() []error { return m }

// FilUsdtReplyValidationError is the validation error returned by
// FilUsdtReply.Validate if the designated constraints aren't met.
type FilUsdtReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilUsdtReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilUsdtReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilUsdtReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilUsdtReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilUsdtReplyValidationError) ErrorName() string { return "FilUsdtReplyValidationError" }

// Error satisfies the builtin error interface
func (e FilUsdtReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilUsdtReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilUsdtReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilUsdtReplyValidationError{}

// Validate checks the field values on FilUsdtReply_ListK with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FilUsdtReply_ListK) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FilUsdtReply_ListK with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FilUsdtReply_ListKMultiError, or nil if none found.
func (m *FilUsdtReply_ListK) ValidateAll() error {
	return m.validate(true)
}

func (m *FilUsdtReply_ListK) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for StartPrice

	// no validation rules for TopPrice

	// no validation rules for LowPrice

	// no validation rules for EndPrice

	// no validation rules for DealTotalAmount

	// no validation rules for DealAmount

	// no validation rules for DealTotal

	// no validation rules for DealSelfTotalAmount

	// no validation rules for DealSelfAmount

	if len(errors) > 0 {
		return FilUsdtReply_ListKMultiError(errors)
	}

	return nil
}

// FilUsdtReply_ListKMultiError is an error wrapping multiple validation errors
// returned by FilUsdtReply_ListK.ValidateAll() if the designated constraints
// aren't met.
type FilUsdtReply_ListKMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FilUsdtReply_ListKMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FilUsdtReply_ListKMultiError) AllErrors() []error { return m }

// FilUsdtReply_ListKValidationError is the validation error returned by
// FilUsdtReply_ListK.Validate if the designated constraints aren't met.
type FilUsdtReply_ListKValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilUsdtReply_ListKValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilUsdtReply_ListKValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilUsdtReply_ListKValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilUsdtReply_ListKValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilUsdtReply_ListKValidationError) ErrorName() string {
	return "FilUsdtReply_ListKValidationError"
}

// Error satisfies the builtin error interface
func (e FilUsdtReply_ListKValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilUsdtReply_ListK.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilUsdtReply_ListKValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilUsdtReply_ListKValidationError{}
